#!/usr/bin/env python3
"""
Fetch a random lunch discussion topic and write it to topic.json.

Sources (in order of preference, picked randomly each run):
  1. https://www.tylervigen.com/spurious/random  — GPT-generated fake papers
  2. https://improbable.com/ig/winners/          — Ig Nobel Prize winners
  3. Built-in fallback list (used when scraping fails)
"""

import json
import re
import random
import sys
from datetime import date, datetime, timezone
from pathlib import Path

try:
    import requests
    from bs4 import BeautifulSoup
    HAS_DEPS = True
except ImportError:
    HAS_DEPS = False
    print("⚠️  requests/beautifulsoup4 not installed. Using fallback topics only.", file=sys.stderr)

# ---------------------------------------------------------------------------
# Curated fallback topics (used if scraping fails or deps missing)
# ---------------------------------------------------------------------------
FALLBACK_TOPICS = [
    {
        "source": "Ig Nobel Prize",
        "year": 2022,
        "category": "Physics",
        "title": "Ducklings swimming in formation behind their mother are surfing her wake",
        "description": "A mathematical and experimental study proved that ducklings in a line formation behind their mother gain a real hydrodynamic advantage: each duckling is effectively 'surfing' on the wave energy generated by the one ahead, reducing drag. The lead position (taken by the mother) is the hardest — which may explain observed duckling jostling behavior.",
        "url": "https://improbable.com/ig/winners/#ig2022",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2022,
        "category": "Economics",
        "title": "A politician's BMI is a reliable proxy for their country's corruption level",
        "description": "Analysis of post-Soviet countries found a statistically significant correlation between the obesity of government politicians (measured from photographs) and standard corruption indices. The paper suggests that in environments with pervasive corruption, officials can more openly display wealth-related behaviors — including weight — without accountability.",
        "url": "https://improbable.com/ig/winners/#ig2022",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2021,
        "category": "Chemistry",
        "title": "The air inside a movie theater accurately reveals the film's age rating",
        "description": "Chemical analysis of volatile organic compounds (VOCs) in cinema air showed that audience metabolic output varies predictably with on-screen content. Violence, sex, drug use, and bad language each produce distinct VOC signatures measurable in real time — suggesting a passive, audience-derived rating system. Tested blind against MPAA ratings with high accuracy.",
        "url": "https://improbable.com/ig/winners/#ig2021",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2021,
        "category": "Medicine",
        "title": "Sexual orgasms can be as effective as nasal decongestants",
        "description": "Researchers measured nasal airflow resistance immediately before and after orgasm, and at intervals up to 60 minutes later. Nasal airflow improvement was comparable to oxymetazoline spray (a standard decongestant) and lasted for approximately 45 minutes. The effect is mediated by the autonomic nervous system. A potentially side-effect-free treatment for chronic nasal congestion.",
        "url": "https://improbable.com/ig/winners/#ig2021",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2021,
        "category": "Peace",
        "title": "Human beards evolved primarily to cushion punches to the face",
        "description": "Using synthetic bone, epoxy matrix, and hair samples, researchers tested whether dense facial hair absorbs impact energy. They found a ~30% reduction in peak force transmitted to the jaw when hair was present. The 'pugilism hypothesis' proposes beards evolved in males as a form of passive facial armor in intraspecific combat, predating grooming norms.",
        "url": "https://improbable.com/ig/winners/#ig2021",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2020,
        "category": "Physics",
        "title": "Why pedestrians do not constantly collide with each other",
        "description": "High-density pedestrian flow experiments and physics-based modelling revealed that collision avoidance emerges from rapid gaze-direction detection and micro-trajectory adjustments happening ~0.5s before impact. The study found that removing this anticipatory step (as can occur with phone distraction) dramatically increases collision rates — aligning with real-world observations about phone usage and pedestrian accidents.",
        "url": "https://improbable.com/ig/winners/#ig2020",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2020,
        "category": "Acoustics",
        "title": "Alligators immersed in helium change their pitch — confirming they use formants to signal body size",
        "description": "Chinese alligators vocalizing in a helium-enriched atmosphere predictably shifted their dominant frequency upward, while fundamental frequency (controlled by the larynx) was unaffected. This isolates formant resonance as the key channel, proving alligators — like humans — communicate size information through vocal tract resonances. Formant-based signalling predates the mammalian lineage by over 200 million years.",
        "url": "https://improbable.com/ig/winners/#ig2020",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2019,
        "category": "Medicine",
        "title": "Roller coasters facilitate the passage of small kidney stones",
        "description": "A urologist noticing patients reporting stone passage after theme park visits ran a controlled study using a 3D-printed kidney model with real kidney stones and urine. Riding in the rear car of Big Thunder Mountain Railroad at Disney World produced a ~64% stone passage rate vs ~17% in the front car. Proposed mechanism: oscillating acceleration disrupting stone-to-wall contact in the ureteropelvic junction.",
        "url": "https://improbable.com/ig/winners/#ig2019",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2019,
        "category": "Biology",
        "title": "Wombats produce cube-shaped feces via elastic intestinal walls — not a cube-shaped sphincter",
        "description": "Wombats are the only animals producing cube-shaped scat. Dissection and modelling revealed the mechanism is not sphincter geometry but variable wall elasticity in the distal intestine: two stiff grooves and two pliable regions alternate around the circumference, sculpting the feces into cubes during the final dehydration phase. The finding suggests a moldless manufacturing technique for soft cubic structures.",
        "url": "https://improbable.com/ig/winners/#ig2019",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2018,
        "category": "Medicine",
        "title": "Ranked: the most painful body locations to be stung by a honey bee",
        "description": "An entomologist allowed himself to be stung by a honey bee on 25 different body locations (three stings each, five times), using a standardised pain scale. The nostril, upper lip, and penis shaft ranked as the most painful. The palm of the hand, skull, and upper arm were least painful. The study used the Schmidt Sting Pain Index methodology and was designed as a rigorous self-experiment.",
        "url": "https://improbable.com/ig/winners/#ig2018",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2017,
        "category": "Physics",
        "title": "Human ears grow at ~0.22 mm per year throughout life — explaining why old men have large ears",
        "description": "A 20-year longitudinal measurement study confirmed that ear size increases continuously across adult life at a consistent rate of 0.22 mm per year. The cartilage does not ossify and continues to grow, unlike most soft tissue. The study used standardised caliper measurements, controlled for sex and age, and found no significant sex difference in growth rate. Ear length is a reliable (if slow) age estimator.",
        "url": "https://improbable.com/ig/winners/#ig2017",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2013,
        "category": "Physics",
        "title": "A fluid dynamics explanation of why coffee spills when you walk",
        "description": "Analysis of the coupled oscillation between a human walking gait (stride frequency ~1–2 Hz) and the natural sloshing resonance of a standard coffee mug found they overlap almost exactly — making spills near-inevitable. The study proposed mitigation strategies: look at the mug, walk backwards (shifts resonance), add a lid, use a non-circular mug, or walk with very small steps. Won wide coverage as an example of useful applied physics.",
        "url": "https://improbable.com/ig/winners/#ig2013",
    },
    {
        "source": "Ig Nobel Prize",
        "year": 2016,
        "category": "Economics",
        "title": "In autocratic organisations, sycophancy outperforms competence as a career strategy",
        "description": "A mathematical model comparing investment in sycophancy (flattering leaders) vs. effort (improving performance) found that sycophancy produces better individual outcomes in any organisation with autocratic incentive structures — despite being collectively harmful. The model predicts a 'sycophancy equilibrium' from which rational actors cannot unilaterally deviate, offering a formal explanation for institutional dysfunction.",
        "url": "https://improbable.com/ig/winners/#ig2016",
    },
    {
        "source": "Spurious Correlation",
        "year": 2014,
        "category": "Statistical Curiosity",
        "title": "Divorce rate in Maine correlates with per capita margarine consumption (r = 0.993)",
        "description": "From 2000–2009, the divorce rate in Maine tracked per capita margarine consumption almost perfectly (Pearson r = 0.993, p < 0.05). A canonical example of how data-mining time series produces arbitrarily strong spurious correlations — both variables independently declined over the decade. Used in statistics curricula worldwide to illustrate the multiple-comparisons problem and the limits of p-values as a quality signal.",
        "url": "https://www.tylervigen.com/spurious-correlations",
    },
    {
        "source": "Spurious Correlation",
        "year": 2014,
        "category": "Statistical Curiosity",
        "title": "Number of Nicolas Cage films correlates with swimming pool drownings (r = 0.666)",
        "description": "The annual count of Nicolas Cage film releases correlated with US swimming pool drowning deaths from 1999–2009 (r = 0.666). A widely shared illustration of the distinction between correlation and causation, and of how any two time series with overlapping trends will yield non-trivial correlation coefficients. Often used in data science onboarding and introductory statistics courses.",
        "url": "https://www.tylervigen.com/spurious-correlations",
    },
    {
        "source": "Spurious Correlation",
        "year": 2014,
        "category": "Statistical Curiosity",
        "title": "US federal science spending correlates with suicides by hanging (r = 0.998)",
        "description": "Total US spending on science, space, and technology tracked suicides by hanging, strangulation, and suffocation at r = 0.998 from 1999–2009. The near-perfect fit — achieved with zero causal mechanism — is a favourite example in discussions about reproducibility, HARKing (Hypothesising After Results Known), and why effect size thresholds alone cannot substitute for theoretical justification.",
        "url": "https://www.tylervigen.com/spurious-correlations",
    },
    {
        "source": "Spurious Correlation",
        "year": 2014,
        "category": "Statistical Curiosity",
        "title": "Per capita cheese consumption correlates with deaths by bedsheet tangling (r = 0.947)",
        "description": "Annual US per capita cheese consumption tracked the number of people who died by becoming tangled in their bedsheets at r = 0.947 from 2000–2009. Both variables grew over the same decade with no possible causal connection. A commonly cited counter-example to the naive claim that 'high correlation means something real', and a useful entry point for discussing confounders and ecological fallacies.",
        "url": "https://www.tylervigen.com/spurious-correlations",
    },
    {
        "source": "Spurious Correlation",
        "year": 2014,
        "category": "Statistical Curiosity",
        "title": "Internet Explorer market share correlates with the US murder rate (r = 0.923)",
        "description": "Internet Explorer's browser market share closely tracked the US murder rate from 2006–2011 (r = 0.923). Both declined independently over the same period. Used as a reductio-ad-absurdum argument against drawing policy conclusions from aggregate trend data without controls, and as a memorable example of why declining macroeconomic indicators often appear correlated with one another.",
        "url": "https://www.tylervigen.com/spurious-correlations",
    },
]

# ---------------------------------------------------------------------------
# Live scrapers
# ---------------------------------------------------------------------------

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; lunchbot/1.0; +https://github.com)"}


def fetch_tylervigen() -> dict | None:
    """
    Fetch a random spurious-correlation paper from tylervigen.com/spurious/random.
    The page renders a GPT-generated fake academic paper; we extract TITLE + ABSTRACT.
    """
    try:
        resp = requests.get(
            "https://www.tylervigen.com/spurious/random",
            headers=HEADERS,
            timeout=15,
            allow_redirects=True,
        )
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")
        text = soup.get_text("\n")

        # The page format (escaped brackets become [[TITLE]] / [[ABSTRACT]] in rendered text)
        title_match = re.search(r"\[\[TITLE\]\]\s*\n+(.+?)(?:\n|$)", text)
        abstract_match = re.search(
            r"\[\[ABSTRACT\]\]\s*\n+(.+?)(?=\n\n|\*\*Model:|\Z)", text, re.DOTALL
        )

        if not title_match or not abstract_match:
            print("tylervigen: could not find [[TITLE]]/[[ABSTRACT]]", file=sys.stderr)
            return None

        title = title_match.group(1).strip()
        abstract = abstract_match.group(1).strip().replace("\n", " ")
        # Truncate gracefully
        if len(abstract) > 600:
            abstract = abstract[:597] + "…"

        if len(title) < 10:
            return None

        # Also try to extract the raw correlation (from the user prompt)
        corr_match = re.search(
            r"connection between (.+?) and (.+?)\.", text, re.IGNORECASE
        )
        if corr_match:
            var_a = corr_match.group(1).strip()
            var_b = corr_match.group(2).strip()
            description = (
                f"[AI-generated paper] The underlying correlation: {var_a} vs {var_b}. "
                + abstract
            )
        else:
            description = "[AI-generated fake academic paper] " + abstract

        return {
            "source": "Spurious Correlation (AI paper)",
            "year": date.today().year,
            "category": "Statistical Curiosity",
            "title": title,
            "description": description[:650],
            "url": str(resp.url),
        }
    except Exception as exc:
        print(f"tylervigen fetch failed: {exc}", file=sys.stderr)
        return None


def fetch_ig_nobel() -> dict | None:
    """
    Fetch a random Ig Nobel winner from improbable.com/ig/winners/.
    The page lists prizes in the format:
        **CATEGORY PRIZE** [COUNTRIES]:
        Researcher names, for doing/discovering X.
    We parse all entries and pick one at random.
    """
    try:
        resp = requests.get(
            "https://improbable.com/ig/winners/",
            headers=HEADERS,
            timeout=15,
        )
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")

        entries = []
        current_year = None

        # Walk all elements looking for year headings and prize paragraphs
        for tag in soup.find_all(["h2", "h3", "p", "li"]):
            text = tag.get_text(" ", strip=True)

            # Year heading: "2023 Ig Nobel Prizes" or just "2023"
            year_match = re.match(r"^((?:19|20)\d{2})\b", text)
            if tag.name in ("h2", "h3") and year_match:
                current_year = int(year_match.group(1))
                continue

            # Prize entry: starts with CATEGORY PRIZE [COUNTRIES]: description
            prize_match = re.match(
                r"([A-Z][A-Z\s]+?)\s+PRIZE\s*\[([^\]]+)\]\s*[:\-–]\s*(.+)",
                text,
                re.DOTALL,
            )
            if prize_match:
                category = prize_match.group(1).title().strip()
                description_raw = prize_match.group(3).strip().replace("\n", " ")
                # Remove trailing reference lines ("REFERENCE: ...")
                description_clean = re.split(r"\s+REFERENCE:", description_raw)[0].strip()
                if len(description_clean) < 40:
                    continue
                # Derive a short title from the "for X" clause
                for_match = re.search(r"\bfor\b (.+?)(?:\.|$)", description_clean, re.IGNORECASE)
                title = for_match.group(1).strip().capitalize() if for_match else description_clean[:80]
                if len(title) > 120:
                    title = title[:117] + "…"
                year = current_year or date.today().year
                entries.append(
                    {
                        "source": "Ig Nobel Prize",
                        "year": year,
                        "category": category,
                        "title": title,
                        "description": description_clean[:600],
                        "url": f"https://improbable.com/ig/winners/{'#ig' + str(year) if current_year else ''}",
                    }
                )

        if entries:
            print(f"ig-nobel: found {len(entries)} entries", file=sys.stderr)
            return random.choice(entries)

        print("ig-nobel: no entries parsed", file=sys.stderr)
        return None
    except Exception as exc:
        print(f"ig-nobel fetch failed: {exc}", file=sys.stderr)
        return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    today = date.today()
    week_num = today.isocalendar()[1]

    pool: list[dict] = []

    if HAS_DEPS:
        # Shuffle fetch order so both sources get equal airtime over time
        fetchers = [fetch_tylervigen, fetch_ig_nobel]
        random.shuffle(fetchers)
        for fetcher in fetchers:
            result = fetcher()
            if result:
                pool.append(result)
                break  # one live result is enough; rest comes from fallback

    # Always add fallback pool so there's always something to pick from
    pool.extend(FALLBACK_TOPICS)

    topic = random.choice(pool)

    output = {
        "title": topic["title"],
        "description": topic["description"],
        "source": topic["source"],
        "year": topic.get("year", today.year),
        "category": topic.get("category", "Research"),
        "url": topic["url"],
        "week": week_num,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

    out_path = Path(__file__).parent.parent / "topic.json"
    out_path.write_text(json.dumps(output, indent=2, ensure_ascii=False) + "\n")
    print(f"✅ topic.json updated — week {week_num}")
    print(f"   [{output['category']}] {output['title'][:80]}")


if __name__ == "__main__":
    main()
